
import type { Campaign } from './types';

export const campaigns: Campaign[] = [
  {
    id: '1',
    title: 'Support for Flood Victims in the North',
    description: 'Urgent funds needed to provide shelter, food, and medical supplies to families affected by the recent devastating floods.',
    fullDescription: 'The recent floods in the northern regions have left thousands of families displaced and without basic necessities. Homes have been washed away, and livelihoods have been destroyed. We are on the ground providing immediate relief, but we need your help. Your donation will provide emergency shelter kits, clean drinking water, non-perishable food items, and essential medical care to those in desperate need. Every contribution, no matter how small, makes a significant impact in helping these communities rebuild their lives.',
    imageUrl: 'https://sdmntprnorthcentralus.oaiusercontent.com/files/00000000-2c98-622f-9175-b6386bb0c36b/raw?se=2025-09-04T09%3A11%3A18Z&sp=r&sv=2024-08-04&sr=b&scid=3adf240c-9425-5d3b-93b0-fa99aa97b924&skoid=5939c452-ea83-4420-b5b4-21182254a5d3&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-09-03T19%3A45%3A18Z&ske=2025-09-04T19%3A45%3A18Z&sks=b&skv=2024-08-04&sig=TXGsDsCSE7v8P9HbE4lLGOA8JwHH2AmKsjnnLCf8Bds%3D',
    targetAmount: 50000,
    raisedAmount: 22500,
    fundraiserName: 'Global Relief Foundation',
    cause: 'Disaster Relief',
    aiHint: 'flood relief',
  },
  {
    id: '2',
    title: 'Help Priya Fight a Rare Medical Condition',
    description: 'Priya, a 10-year-old girl, is battling a rare disease. Her family needs help to cover the costs of her treatment.',
    fullDescription: 'Priya has been diagnosed with a rare genetic disorder that requires ongoing specialized treatment not covered by insurance. Her family has exhausted their savings, and they are now facing the immense financial burden of her medical bills. The treatment is crucial for her quality of life and future. We are raising funds to cover her hospital stays, medication, and therapy sessions. Your support can give Priya a fighting chance and bring hope to her family during this incredibly difficult time.',
    imageUrl: 'https://sdmntprwestus.oaiusercontent.com/files/00000000-2e54-6230-bfa2-b4da781fc4b9/raw?se=2025-09-04T09%3A02%3A31Z&sp=r&sv=2024-08-04&sr=b&scid=c0b58591-cfd7-5f93-a6fd-04025e4c15a9&skoid=03727f49-62d3-42ac-8350-1c0e6559d238&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-09-03T22%3A07%3A44Z&ske=2025-09-04T22%3A07%3A44Z&sks=b&skv=2024-08-04&sig=4t9eobAWUDnA8UmtVryEBCFav/tECv%2Bi2EN5vteLBYE%3D',
    targetAmount: 75000,
    raisedAmount: 61000,
    fundraiserName: 'Friends of Priya',
    cause: 'Medical',
    aiHint: 'sick child',
  },
  {
    id: '3',
    title: 'Build a Digital Library for Rural Students',
    description: 'Provide access to digital educational resources for over 500 students in a remote village school.',
    fullDescription: 'In today\'s digital world, access to information is key to a good education. Unfortunately, students in many rural areas lack access to the digital resources that are standard elsewhere. We aim to change that by building a fully-equipped digital library for a school in a remote village. The funds will be used to purchase computers, tablets, internet access, and educational software subscriptions. This project will open up a world of knowledge for over 500 students, empowering them to learn, grow, and achieve their dreams.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
    targetAmount: 20000,
    raisedAmount: 8200,
    fundraiserName: 'Educate Future Foundation',
    cause: 'Education',
    aiHint: 'rural school',
  },
  {
    id: '4',
    title: 'Emergency Vet Care for Strays',
    description: 'Support our mission to provide life-saving veterinary care for injured and sick stray animals.',
    fullDescription: 'Our city\'s streets are home to countless stray animals who often suffer from injuries, illness, and malnutrition. Our small team of volunteers works tirelessly to rescue these animals and provide them with the care they need. However, vet bills for emergency surgeries, medications, and vaccinations are a constant challenge. This campaign will help us create a dedicated fund for emergency veterinary care, ensuring that we never have to turn away an animal in critical condition. Your donation saves lives.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
    targetAmount: 15000,
    raisedAmount: 14500,
    fundraiserName: 'Street Paws Rescue',
    cause: 'Personal',
    aiHint: 'stray dog',
  },
  {
    id: '5',
    title: 'Support an Aspiring Artist\'s First Exhibition',
    description: 'Help a talented young artist showcase their work to the world by funding their first solo art exhibition.',
    fullDescription: 'Every artist dreams of their first solo exhibition, a chance to share their vision with the world. We are raising funds for a gifted young painter who has a remarkable body of work but lacks the financial resources to rent a gallery space, frame their art, and promote the event. This is a unique opportunity to directly support emerging talent and help launch a promising career in the arts. Your contribution will help cover all the essential costs of making this exhibition a reality.',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    targetAmount: 10000,
    raisedAmount: 3000,
    fundraiserName: 'Creative Futures Collective',
    cause: 'Personal',
    aiHint: 'art exhibition',
  },
  {
    id: '6',
    title: 'Clean Water Project for a Community in Need',
    description: 'Fund the installation of a new well and water purification system for a village without access to clean drinking water.',
    fullDescription: 'Access to clean water is a basic human right, yet many communities still struggle to find it. We have identified a village where residents, mostly children and women, walk several miles each day to collect water from a contaminated source, leading to widespread waterborne diseases. This project will fund the drilling of a new deep-water well and the installation of a solar-powered purification system. This will provide the entire community with a sustainable source of safe, clean drinking water, dramatically improving health and quality of life.',
    imageUrl: 'https://sdmntprwestus.oaiusercontent.com/files/00000000-1f24-6230-9e43-5a5e27099bd9/raw?se=2025-09-04T09%3A10%3A38Z&sp=r&sv=2024-08-04&sr=b&scid=8dd6701d-45ad-56c6-a931-e281c89db84a&skoid=03727f49-62d3-42ac-8350-1c0e6559d238&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-09-03T21%3A45%3A21Z&ske=2025-09-04T21%3A45%3A21Z&sks=b&skv=2024-08-04&sig=ad1A1PfVDBaqdSmp1uVwoWZgkFWEZ%2BhtDMrJBw9gbrc%3D',
    targetAmount: 40000,
    raisedAmount: 15000,
    fundraiserName: 'Water for Life Initiative',
    cause: 'Disaster Relief',
    aiHint: 'clean water',
  },
  {
    id: '7',
    title: 'Digital Classrooms for a Village School in Rajasthan',
    description: 'Help us equip a rural school in Rajasthan with smart boards and tablets to bridge the digital divide.',
    fullDescription: 'We believe that every child deserves a modern education. This project aims to bring digital learning to a government school in a remote village in Rajasthan, providing students with tools that will prepare them for the future. The funds will be used to purchase interactive smart boards, tablets for students, and provide training for teachers.',
    imageUrl: 'https://sdmntprukwest.oaiusercontent.com/files/00000000-4624-6243-ba3b-61253c3e5f59/raw?se=2025-09-04T08%3A51%3A16Z&sp=r&sv=2024-08-04&sr=b&scid=d8cdfcd0-8d7a-5ebe-b060-bfb0ce507600&skoid=5939c452-ea83-4420-b5b4-21182254a5d3&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-09-03T22%3A13%3A35Z&ske=2025-09-04T22%3A13%3A35Z&sks=b&skv=2024-08-04&sig=40%2BxbC3U8wauT8/9gdgapJYxZAB9qPeNwW03qiqIPdY%3D',
    targetAmount: 35000,
    raisedAmount: 11200,
    fundraiserName: 'Rajasthan Education Trust',
    cause: 'Education',
    aiHint: 'digital classroom',
  },
  {
    id: '8',
    title: 'Mobile Health Clinic for Rural West Bengal',
    description: 'Fund a mobile health unit to provide essential medical care to remote villages in West Bengal.',
    fullDescription: 'Many villages in West Bengal lack access to even basic healthcare facilities. This campaign will fund a fully-equipped mobile health clinic that will travel to these remote areas, offering free check-ups, essential medicines, and health awareness programs to thousands of people.',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    targetAmount: 85000,
    raisedAmount: 42000,
    fundraiserName: 'Bengal Health Initiative',
    cause: 'Medical',
    aiHint: 'mobile clinic',
  },
  {
    id: '9',
    title: 'Cyclone Relief for Coastal Communities in Odisha',
    description: 'Provide immediate relief and long-term rebuilding support to families affected by the recent cyclone in Odisha.',
    fullDescription: 'Coastal Odisha has been hit by a severe cyclone, causing widespread destruction. Families have lost their homes and livelihoods. Your donation will help us provide immediate aid like food, water, and shelter, as well as support long-term recovery efforts such as rebuilding houses and restoring fishing businesses.',
    imageUrl: 'https://picsum.photos/600/400?random=9',
    targetAmount: 100000,
    raisedAmount: 37500,
    fundraiserName: 'Odisha Rebuilds',
    cause: 'Disaster Relief',
    aiHint: 'cyclone relief',
  },
  {
    id: '10',
    title: 'Restore a Community Library in Kerala',
    description: 'Help us rebuild and restock a beloved community library in Kerala that was damaged in a fire.',
    fullDescription: 'The "People\'s Library" has been a hub of knowledge and community for decades. A recent fire has destroyed most of its collection and damaged the building. We are raising funds to repair the library, purchase new books, and create a safe and welcoming space for readers of all ages.',
    imageUrl: 'https://picsum.photos/600/400?random=10',
    targetAmount: 25000,
    raisedAmount: 9800,
    fundraiserName: 'Friends of the People\'s Library',
    cause: 'Personal',
    aiHint: 'community library',
  },
  {
    id: '11',
    title: 'Reforestation Drive in the Aravalli Hills',
    description: 'Join our mission to plant 10,000 native trees in the Aravalli range to combat desertification and restore biodiversity.',
    fullDescription: 'The Aravalli hills, one of the world\'s oldest mountain ranges, are facing severe degradation. This project aims to carry out a large-scale reforestation drive, planting native species that will help recharge groundwater, prevent soil erosion, and bring back wildlife to the region. Your support will help us buy saplings and fund the plantation effort.',
    imageUrl: 'https://picsum.photos/600/400?random=11',
    targetAmount: 18000,
    raisedAmount: 5500,
    fundraiserName: 'Green Aravalli',
    cause: 'Education',
    aiHint: 'reforestation drive',
  },
  {
    id: '12',
    title: 'Life-Saving Surgery for a Child in Mumbai',
    description: 'Help 5-year-old Rohan get the urgent open-heart surgery he needs to survive.',
    fullDescription: 'Rohan was born with a critical congenital heart defect and needs immediate surgery to save his life. His family works as a daily wage earners and cannot afford the high cost of the operation. Every rupee brings us closer to giving this child a chance at a healthy future.',
    imageUrl: 'https://picsum.photos/600/400?random=12',
    targetAmount: 90000,
    raisedAmount: 71000,
    fundraiserName: 'Save Rohan\'s Heart',
    cause: 'Medical',
    aiHint: 'child surgery',
  },
  {
    id: '13',
    title: 'Winter Kits for Delhi\'s Homeless',
    description: 'Provide warm blankets, clothing, and meals to those living on the streets of Delhi during the harsh winter.',
    fullDescription: 'Winter in Delhi is unforgiving, especially for the thousands who have no roof over their heads. This campaign will distribute winter survival kits containing a warm blanket, a jacket, socks, and a hot meal to the most vulnerable. Your small contribution can provide life-saving warmth and comfort.',
    imageUrl: 'https://picsum.photos/600/400?random=13',
    targetAmount: 12000,
    raisedAmount: 11500,
    fundraiserName: 'Delhi Winter Care',
    cause: 'Disaster Relief',
    aiHint: 'homeless winter',
  },
  {
    id: '14',
    title: 'Vocational Training for Women in Uttar Pradesh',
    description: 'Empower women in rural Uttar Pradesh with tailoring and handicraft skills to help them achieve financial independence.',
    fullDescription: 'We are setting up a vocational training center to provide women with practical skills that can help them earn a livelihood. This project will fund sewing machines, raw materials, and instructor fees. Empowering a woman means empowering a family and a community.',
    imageUrl: 'https://picsum.photos/600/400?random=14',
    targetAmount: 30000,
    raisedAmount: 12500,
    fundraiserName: 'UP Women Empowerment',
    cause: 'Personal',
    aiHint: 'vocational training',
  },
  {
    id: '15',
    title: 'Prosthetic Limbs for Landmine Victims',
    description: 'Provide high-quality prosthetic limbs to amputees in conflict-affected regions, giving them the gift of mobility.',
    fullDescription: 'In many parts of our country, unexploded landmines continue to injure innocent civilians long after conflicts have ended. This campaign provides custom-fitted, high-quality prosthetic limbs to those who have lost their legs or arms, helping them regain their independence, dignity, and ability to work.',
    imageUrl: 'https://picsum.photos/600/400?random=15',
    targetAmount: 60000,
    raisedAmount: 28000,
    fundraiserName: 'Mobility India Foundation',
    cause: 'Medical',
    aiHint: 'prosthetic limb',
  },
  {
    id: '16',
    title: 'Support Traditional Folk Artists of Rajasthan',
    description: 'Help preserve the dying art forms of Rajasthan by providing financial support to aging folk musicians and artists.',
    fullDescription: 'The rich folk traditions of Rajasthan are at risk of disappearing as artists struggle to make ends meet. This fund will provide a monthly stipend to master artists, ensuring their knowledge is passed down to the next generation and their basic needs are met. Help us save a priceless part of India\'s cultural heritage.',
    imageUrl: 'https://picsum.photos/600/400?random=16',
    targetAmount: 22000,
    raisedAmount: 7800,
    fundraiserName: 'Rajasthan Heritage Fund',
    cause: 'Personal',
    aiHint: 'folk artists',
  },
  {
    id: '17',
    title: 'Science Labs for a School in Chennai',
    description: 'Equip a low-income school in Chennai with modern physics, chemistry, and biology labs.',
    fullDescription: 'Practical learning is essential for science education. We are fundraising to build and equip full-fledged science labs for a secondary school that serves underprivileged students in Chennai. This will give them hands-on experience and ignite a passion for science and innovation.',
    imageUrl: 'https://picsum.photos/600/400?random=17',
    targetAmount: 45000,
    raisedAmount: 19500,
    fundraiserName: 'Chennai Science Initiative',
    cause: 'Education',
    aiHint: 'science lab',
  },
  {
    id: '18',
    title: 'Drought Relief for Farmers in Maharashtra',
    description: 'Provide emergency financial aid and cattle fodder to farmers in drought-stricken regions of Maharashtra.',
    fullDescription: 'Successive years of low rainfall have created a severe drought crisis in Maharashtra, pushing farmers into debt and despair. This campaign will provide direct cash transfers to the worst-affected families and supply fodder for their livestock, offering a lifeline in their time of need.',
    imageUrl: 'https://picsum.photos/600/400?random=18',
    targetAmount: 70000,
    raisedAmount: 31000,
    fundraiserName: 'Farmer Aid Maharashtra',
    cause: 'Disaster Relief',
    aiHint: 'drought relief',
  },
  {
    id: '19',
    title: 'Solar Panels for a Remote Himalayan Village',
    description: 'Bring clean and reliable electricity to a remote village in the Himalayas by installing a solar micro-grid.',
    fullDescription: 'A village nestled deep in the Himalayas has lived without electricity for centuries. We aim to change that by installing a community-owned solar micro-grid. This will power homes, a school, and a health clinic, transforming the lives of the villagers and opening up new opportunities.',
    imageUrl: 'https://picsum.photos/600/400?random=19',
    targetAmount: 55000,
    raisedAmount: 25000,
    fundraiserName: 'Himalayan Light Project',
    cause: 'Education',
    aiHint: 'solar panels',
  },
  {
    id: '20',
    title: 'Mental Health Support for Students',
    description: 'Fund a free counseling and mental health support program for university students facing academic stress and anxiety.',
    fullDescription: 'The pressures of higher education can take a huge toll on students\' mental well-being. This program will offer free, confidential counseling services and workshops on stress management and mental wellness on university campuses. Your support can help students thrive, not just survive.',
    imageUrl: 'https://picsum.photos/600/400?random=20',
    targetAmount: 28000,
    raisedAmount: 14000,
    fundraiserName: 'Student Wellness Network',
    cause: 'Medical',
    aiHint: 'mental health',
  },
  {
    id: '21',
    title: 'Preserve the Ancient Art of Varanasi Weaving',
    description: 'Support the weaver community of Varanasi to keep the traditional art of Banarasi silk weaving alive.',
    fullDescription: 'The intricate art of Banarasi silk weaving is facing threats from mass-produced textiles. This project supports the artisan community by providing them with better looms, quality raw materials, and direct access to markets, ensuring they get a fair price for their incredible craftsmanship.',
    imageUrl: 'https://picsum.photos/600/400?random=21',
    targetAmount: 32000,
    raisedAmount: 11000,
    fundraiserName: 'Varanasi Weaver Trust',
    cause: 'Personal',
    aiHint: 'silk weaving',
  },
];
