import type { Campaign } from './types';

export const campaigns: Campaign[] = [
  {
    id: '1',
    title: 'Support for Flood Victims in the North',
    description: 'Urgent funds needed to provide shelter, food, and medical supplies to families affected by the recent devastating floods.',
    fullDescription: 'The recent floods in the northern regions have left thousands of families displaced and without basic necessities. Homes have been washed away, and livelihoods have been destroyed. We are on the ground providing immediate relief, but we need your help. Your donation will provide emergency shelter kits, clean drinking water, non-perishable food items, and essential medical care to those in desperate need. Every contribution, no matter how small, makes a significant impact in helping these communities rebuild their lives.',
    imageUrl: 'https://picsum.photos/600/400?random=1',
    targetAmount: 50000,
    raisedAmount: 22500,
    fundraiserName: 'Global Relief Foundation',
    cause: 'Disaster Relief',
  },
  {
    id: '2',
    title: 'Help Priya Fight a Rare Medical Condition',
    description: 'Priya, a 10-year-old girl, is battling a rare disease. Her family needs help to cover the costs of her treatment.',
    fullDescription: 'Priya has been diagnosed with a rare genetic disorder that requires ongoing specialized treatment not covered by insurance. Her family has exhausted their savings, and they are now facing the immense financial burden of her medical bills. The treatment is crucial for her quality of life and future. We are raising funds to cover her hospital stays, medication, and therapy sessions. Your support can give Priya a fighting chance and bring hope to her family during this incredibly difficult time.',
    imageUrl: 'https://picsum.photos/600/400?random=2',
    targetAmount: 75000,
    raisedAmount: 61000,
    fundraiserName: 'Friends of Priya',
    cause: 'Medical',
  },
  {
    id: '3',
    title: 'Build a Digital Library for Rural Students',
    description: 'Provide access to digital educational resources for over 500 students in a remote village school.',
    fullDescription: 'In today\'s digital world, access to information is key to a good education. Unfortunately, students in many rural areas lack access to the digital resources that are standard elsewhere. We aim to change that by building a fully-equipped digital library for a school in a remote village. The funds will be used to purchase computers, tablets, internet access, and educational software subscriptions. This project will open up a world of knowledge for over 500 students, empowering them to learn, grow, and achieve their dreams.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
    targetAmount: 20000,
    raisedAmount: 8200,
    fundraiserName: 'Educate Future Foundation',
    cause: 'Education',
  },
  {
    id: '4',
    title: 'Emergency Vet Care for Strays',
    description: 'Support our mission to provide life-saving veterinary care for injured and sick stray animals.',
    fullDescription: 'Our city\'s streets are home to countless stray animals who often suffer from injuries, illness, and malnutrition. Our small team of volunteers works tirelessly to rescue these animals and provide them with the care they need. However, vet bills for emergency surgeries, medications, and vaccinations are a constant challenge. This campaign will help us create a dedicated fund for emergency veterinary care, ensuring that we never have to turn away an animal in critical condition. Your donation saves lives.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
    targetAmount: 15000,
    raisedAmount: 14500,
    fundraiserName: 'Street Paws Rescue',
    cause: 'Personal',
  },
  {
    id: '5',
    title: 'Support an Aspiring Artist\'s First Exhibition',
    description: 'Help a talented young artist showcase their work to the world by funding their first solo art exhibition.',
    fullDescription: 'Every artist dreams of their first solo exhibition, a chance to share their vision with the world. We are raising funds for a gifted young painter who has a remarkable body of work but lacks the financial resources to rent a gallery space, frame their art, and promote the event. This is a unique opportunity to directly support emerging talent and help launch a promising career in the arts. Your contribution will help cover all the essential costs of making this exhibition a reality.',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    targetAmount: 10000,
    raisedAmount: 3000,
    fundraiserName: 'Creative Futures Collective',
    cause: 'Personal',
  },
  {
    id: '6',
    title: 'Clean Water Project for a Community in Need',
    description: 'Fund the installation of a new well and water purification system for a village without access to clean drinking water.',
    fullDescription: 'Access to clean water is a basic human right, yet many communities still struggle to find it. We have identified a village where residents, mostly children and women, walk several miles each day to collect water from a contaminated source, leading to widespread waterborne diseases. This project will fund the drilling of a new deep-water well and the installation of a solar-powered purification system. This will provide the entire community with a sustainable source of safe, clean drinking water, dramatically improving health and quality of life.',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    targetAmount: 40000,
    raisedAmount: 15000,
    fundraiserName: 'Water for Life Initiative',
    cause: 'Disaster Relief',
  },
];
